name = "website-database"
compatibility_date = "2024-11-13"

[[r2_buckets]]
binding = "R2"
bucket_name = "central"

[[d1_databases]]
binding = "DB"
database_name = "personal-web"
database_id = "cabaa840-522a-42e0-86f4-6309cfdacc79"

[[d1_databases]]
binding = "DB_PREVIEW"
database_name = "personal-web-preview"
database_id = "55da8048-c4ce-4d4d-9888-74ffb07bf6a7"