name = "website-multiplayer"
compatibility_date = "2024-05-01"

[[durable_objects.bindings]]
name = "MULTIPLAYER"
class_name = "Multiplayer"

[[migrations]]
tag = "v1"
new_classes = ["Multiplayer"]

[dev]
port = 8786

routes = [
  { pattern = "website-multiplayer.nickgriffin.uk", custom_domain = true }
]

[ai]
binding = "AI"