name = "website-blog-api"
compatibility_date = "2024-05-01"

[dev]
port = 8786

routes = [
	{ pattern = "blog.s3rve.co.uk", custom_domain = true }
]

[[r2_buckets]]
binding = 'BUCKET'
bucket_name = 'blog'
preview_bucket_name = 'blog'